### PR TITLE
removed nullable types work

### PR DESCRIPTION
**Pull request by StellarwhimsRepo**
hey i like the idea of this cron_job mod and was trying to get something that worked with cronos. these changes work and i mostly just thought to bring it to your attention. 

while not as elegant as working with nullable types,  perhaps you know how to use nullable types to make similar changes.

the changes are centered around the change on line 42 of cronmanager.cs. using DateTime.SpecifyKind to satisfy the error messages from using the schedule as your examples show in your readme. hope this helps. and of course feel free to discard/edit this as it was only made to show you what i got working.

### CODE REVIEW

**Comment by JereKuusela** [comment]
Thanks for the help. However after adding time zone support I think the error should go away. Is this something you could test?

**Comment by StellarwhimsRepo** [comment]
sure i'll see if i can test.

**Comment by StellarwhimsRepo** [comment]
ok i synced these changes to your main on my fork and updated the references, got a successful build.  unfortunately on my test server the error persists.

image

**Comment by JereKuusela** [comment]
I looked at your changes and I think I understand the issue now. Any chance you could try with the latest? For some reason I haven't been able to get the error at all.

**Pull request closed without merging**
